
project_id = "qwlotordnpeaahjtqyel"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-content]
verify_jwt = true

[functions.parse-cv]
verify_jwt = true

[functions.parse-pdf]
verify_jwt = true

[functions.handle-subscription-success]
verify_jwt = true

[functions.auto-expire-subscriptions]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[auth]
enabled = true
additional_redirect_urls = ["https://lovable.dev"]
site_url = "http://127.0.0.1:3000"
api_url = "http://127.0.0.1:54321"
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_runtime]
policy = "oneshot"
