
import React from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';
import SEOHead from '../components/SEOHead';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowRight, User, Briefcase, Heart, Camera } from 'lucide-react';

const Examples = () => {
  const bioExamples = [
    {
      platform: 'LinkedIn',
      icon: <Briefcase className="w-5 h-5" />,
      category: 'Professional',
      example: "Marketing Director with 8+ years of experience driving growth for Fortune 500 companies. Passionate about data-driven strategies and building high-performing teams. Led campaigns that generated $50M+ in revenue. Always looking to connect with fellow marketers and innovators.",
      tone: 'Professional'
    },
    {
      platform: 'Twitter',
      icon: <User className="w-5 h-5" />,
      category: 'Social',
      example: "Software engineer by day, indie game developer by night 🎮 Building the future one line of code at a time ✨ Coffee enthusiast ☕ Based in Seattle 🌲",
      tone: 'Casual'
    },
    {
      platform: 'Instagram',
      icon: <Camera className="w-5 h-5" />,
      category: 'Creative',
      example: "📸 Travel photographer capturing moments around the world\n✈️ 40+ countries and counting\n🌅 Chasing golden hours and perfect shots\n📍 Currently exploring Japan",
      tone: 'Creative'
    },
    {
      platform: 'Dating App',
      icon: <Heart className="w-5 h-5" />,
      category: 'Personal',
      example: "Adventure seeker who loves hiking, trying new restaurants, and terrible dad jokes. I'm a software engineer who can fix your computer but probably can't fix my cooking. Looking for someone to laugh at my jokes and explore the city with!",
      tone: 'Fun'
    }
  ];

  const coverLetterExample = `Dear Hiring Manager,

I am writing to express my strong interest in the Senior Marketing Manager position at TechCorp. With over 6 years of experience in digital marketing and a proven track record of driving growth for technology companies, I am excited about the opportunity to contribute to your team's continued success.

In my current role as Marketing Manager at StartupXYZ, I have:
• Increased lead generation by 150% through strategic content marketing campaigns
• Managed a $500K annual marketing budget with a 4:1 ROI
• Led a team of 5 marketing specialists to launch 3 successful product campaigns
• Implemented marketing automation that reduced customer acquisition cost by 30%

What particularly excites me about TechCorp is your commitment to innovation and customer-centric approach. Your recent expansion into AI-powered solutions aligns perfectly with my experience in emerging technology marketing, where I successfully launched a machine learning product that generated $2M in first-year revenue.

I would welcome the opportunity to discuss how my passion for data-driven marketing and proven leadership skills can contribute to TechCorp's growth objectives. Thank you for considering my application.

Best regards,
Sarah Johnson`;

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <SEOHead
        title="Examples - Professional Bio and Cover Letter Samples | MakeMy.Bio"
        description="Browse real examples of AI-generated professional bios for LinkedIn, Twitter, Instagram, dating apps, and cover letters. Get inspiration for your own content."
        keywords="bio examples, cover letter examples, LinkedIn bio samples, professional bio templates, resume examples"
        canonicalUrl="https://makemy.bio/examples"
      />
      <Header />
      
      <main className="flex-grow py-12 px-6">
        <div className="container mx-auto max-w-6xl">
          {/* Header Section */}
          <div className="text-center mb-16">
            <h1 className="font-serif text-4xl md:text-5xl font-bold mb-6">
              Real <span className="text-gradient">Examples</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
              See what our AI can create for you. These are real examples generated by our platform for different platforms and purposes.
            </p>
            <Link to="/bio-generator">
              <Button size="lg" className="bg-gradient-to-r from-makemybio-purple to-makemybio-pink hover:opacity-90">
                Create Your Own Bio
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </Link>
          </div>

          {/* Bio Examples Section */}
          <section className="mb-16">
            <h2 className="text-3xl font-bold text-center mb-12">Bio Examples</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {bioExamples.map((example, index) => (
                <Card key={index} className="border-2 hover:border-makemybio-purple/30 transition-all duration-200">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-3">
                      {example.icon}
                      <span>{example.platform}</span>
                      <Badge variant="outline" className="ml-auto">
                        {example.tone}
                      </Badge>
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="bg-muted rounded-lg p-4 mb-4">
                      <p className="text-sm whitespace-pre-line leading-relaxed">
                        {example.example}
                      </p>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Category: {example.category}
                    </p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </section>

          {/* Cover Letter Example Section */}
          <section className="mb-16">
            <h2 className="text-3xl font-bold text-center mb-12">Cover Letter Example</h2>
            <div className="max-w-4xl mx-auto">
              <Card className="border-2">
                <CardHeader>
                  <CardTitle className="flex items-center gap-3">
                    <Briefcase className="w-5 h-5" />
                    <span>Senior Marketing Manager Application</span>
                    <Badge variant="outline" className="ml-auto">
                      Professional
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="bg-muted rounded-lg p-6">
                    <pre className="text-sm whitespace-pre-wrap leading-relaxed font-sans">
                      {coverLetterExample}
                    </pre>
                  </div>
                  <p className="text-xs text-muted-foreground mt-4">
                    This cover letter was generated using our AI with specific job requirements and candidate background information.
                  </p>
                </CardContent>
              </Card>
            </div>
          </section>

          {/* CTA Section */}
          <section className="text-center bg-gradient-to-br from-makemybio-purple/5 to-makemybio-pink/5 rounded-3xl p-12">
            <h3 className="text-2xl font-bold mb-4">Ready to create your own?</h3>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
              Get started with our AI-powered bio and cover letter generator. Create professional content in seconds.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/bio-generator">
                <Button size="lg" className="bg-gradient-to-r from-makemybio-purple to-makemybio-pink hover:opacity-90">
                  Generate Bio
                </Button>
              </Link>
              <Link to="/cover-letter">
                <Button size="lg" variant="outline">
                  Create Cover Letter
                </Button>
              </Link>
            </div>
          </section>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Examples;
