
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import SEOHead from '../components/SEOHead';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const FAQ = () => {
  const faqs = [
    {
      question: "How does WordCraft generate content?",
      answer: "WordCraft uses OpenAI's advanced language models to analyze the information you provide and generate personalized, professional content tailored to your specific needs and the platform you're targeting."
    },
    {
      question: "Is my information secure?",
      answer: "Yes. We don't store your personal information longer than necessary to provide our service. Your data is encrypted and never shared with third parties."
    },
    {
      question: "How accurate is the generated content?",
      answer: "WordCraft produces high-quality content based on the information you provide. For best results, provide specific and detailed information in the form. You can always edit the generated content to perfect it."
    },
    {
      question: "Can I use the generated content commercially?",
      answer: "Yes. All content generated by WordCraft is yours to use however you like, including for commercial purposes."
    },
    {
      question: "Do you offer customer support?",
      answer: "Absolutely! You can contact us through our support email, and we'll get back to you within 24 hours."
    },
    {
      question: "Is there a limit to how many bios or cover letters I can generate?",
      answer: "On free accounts, there's a daily limit of 3 generations. Premium accounts have higher or unlimited generations depending on the plan."
    },
    {
      question: "Can I get a refund if I'm not satisfied?",
      answer: "Yes, we offer a 14-day money-back guarantee on all premium plans if you're not completely satisfied with our service."
    },
    {
      question: "Do you have templates for specific industries?",
      answer: "Yes, our AI is trained on content from various industries and can tailor content specifically for your field. Simply mention your industry in the form."
    }
  ];

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "name": "WordCraft FAQ",
    "description": "Frequently asked questions about WordCraft's AI-powered bio and cover letter generator",
    "url": "https://wordcraft.ai/faq",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer
      }
    }))
  };

  return (
    <div className="flex flex-col min-h-screen">
      <SEOHead
        title="Frequently Asked Questions - WordCraft Help Center"
        description="Find answers to common questions about WordCraft's AI-powered bio and cover letter generator. Learn about pricing, features, security, and more."
        keywords="WordCraft FAQ, bio generator help, cover letter generator questions, AI writing tool FAQ, WordCraft support"
        canonicalUrl="https://wordcraft.ai/faq"
        structuredData={structuredData}
      />
      <Header />
      <main className="flex-grow py-12 px-4">
        <div className="container mx-auto">
          <div className="max-w-4xl mx-auto">
            <header className="text-center mb-12">
              <h1 className="font-serif text-3xl md:text-4xl font-bold mb-4">
                Frequently Asked Questions
              </h1>
              <p className="text-muted-foreground md:text-lg max-w-2xl mx-auto">
                Find answers to common questions about WordCraft and our services.
              </p>
            </header>
            
            <div className="bg-card rounded-xl p-6 shadow-sm">
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left font-medium">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
            
            <section className="mt-12 text-center">
              <h2 className="text-xl font-semibold mb-4">Still have questions?</h2>
              <p className="text-muted-foreground mb-4">
                Contact us at support@wordcraft.ai and we'll get back to you as soon as possible.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default FAQ;
