// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlotordnpeaahjtqyel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bG90b3JkbnBlYWFoanRxeWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTI2NDEsImV4cCI6MjA2MzM4ODY0MX0.3adFjLJAMf9ZYyLRR6WN9qEaA1MSA1XefsoSQXr8q3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);