
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlotordnpeaahjtqyel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bG90b3JkbnBlYWFoanRxeWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjM1NjYsImV4cCI6MjA2MzkzOTU2Nn0.6W3apiGyz3-i6cDYREMQWyQJ4KI6DhM4oU8cnCYCcms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
